##########################
#definicion de variables
##########################
double a;
double b;
double c;
double d;
int e;
int f;
##########################
# programa principal
##########################
void main()
{

a = 3.0 + 4; 

c=  e + f;

a= 4+6.6;

b = 5+b;

d= 3+a;

e = 4+7;

#b = 5.0 * (2.0+6);

#c = 45 /5;

#d = (25 * (6/3))  ^ 2; 
}
#########################
# Fin del programa
#########################